apiVersion: rbac.authorization.k8s.io/v1
kind: Cluster
metadata:
  name: ElasticSearch
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "watch", "list"]
  