apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: logging-sc
provisioner: kubernetes.io/aws-ebs # AWS EBS
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
